### ISSUE TITLE
BUGZ

### ISSUE THREAD

**Issue by rodaues** [Th3-Fr3d/pmdbs#174]
-> register online:
ip
port
masteruname
(masterpassword)
email
nickname (optional), if("")->"User"

-> twofactor!
       -> code / activate account
             ->login
                  ->sync data
                          ->disconnect

-----------------

->settings-onlinelogin = onlinelogin (account vorhanden) (input: masterusername[onlineaccount], masterpw[onlineaccount])
      -> connect()
                 -> login()
                          -> TFA -> code
                                 -> confirm new device(code) (NetworkAdapter.MethodProvider)                              
-> local pw change masterpw (online account) if(!firstUsage)
                                         -> syncing data 
                  -> logout()
      -> disconnect

**Comment by rodaues** [comment]
~MOIN!~
~NEXT->> Sync.finish()~

~PDTPClient DTARET handle UPDATE, SELECT, DELETING_COMPLETED cases~

**Comment by rodaues** [comment]
~COMPLETE loginonline.java !!!~

**Comment by rodaues** [comment]
~-> fix login_online ignoring "SEND_VERIFICATION_NEW_DEVICE" (Taskframework continuing with next task instead waiting for login to complete)~

**Comment by frederik-hoeft** [comment]
~SERVER ---> AUTHORIZATION SUCCESSFUL   ---> x:38624
SERVER <--- LOGIN REQUEST              <--- x:38624
SERVER <-#- [ERRNO 24] DVFY            -#-> x:38624
SERVER <--- REQUEST ACCOUNT DATA       <--- x:38624
SERVER <--- DB-QUERY: SYNCHRONIZE      <--- x:38624
SERVER <-#- [ERRNO 13] NLGI            -#-> x:38624
SERVER ---> VERIFICATION MAIL SENT     ---> x:38624
SERVER <-#- [ERRNO 13] NLGI            -#-> x:38624~

**Comment by rodaues** [comment]
PLS FIX!!

E/AndroidRuntime: FATAL EXCEPTION: Thread-7
    Process: com.example.rodaues.pmdbs_navdraw, PID: 31501
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.example.rodaues.pmdbs_navdraw.Sync.initialize(Sync.java:89)
        at com.example.rodaues.pmdbs_navdraw.SyncThreadHelper.run(SyncThreadHelper.java:23)
        at java.lang.Thread.run(Thread.java:919)

**Comment by rodaues** [comment]
fab_sync only redirects to registeronline.java even though wasOnline ***should*** be true

**Comment by rodaues** [comment]
- ~~executing twice on startup -> UpdateDATASET !!!!~~
- ~~setHID VS. Sync.finish() race condition~~
- move scrypt-hashing to background worker
- ~~setHID not working~~
- random ERR-messages during register sync (local entries exist)
- online login: decryption error!

**Comment by rodaues** [comment]
- sync on register-online not working (not uploading) --> fixed on windows (reschedule bug in tfa)
- ~~update subtringing of hashes~~

**Comment by frederik-hoeft** [comment]
Windows register with data upload, android online login data download:

Android crash in sync (integer parsing and check equal 1)

Server log:
```
SERVER <-#- [ERRNO 24] DVFY            -#-> 192.168.178.51:46384
SERVER ---> VERIFICATION MAIL SENT     ---> 192.168.178.51:46384
SERVER <--- VALIDATE NEW DEVICE        <--- 192.168.178.51:46384
SERVER ---> LOGIN SUCCESSFUL           ---> 192.168.178.51:46384
SERVER <--- REQUEST ACCOUNT DATA       <--- 192.168.178.51:46384
SERVER ---> ACCOUNT DATA               ---> 192.168.178.51:46384
SERVER <--- DB-QUERY: SYNCHRONIZE      <--- 192.168.178.51:46384
SERVER ---> RETURNED SYNDATA           ---> 192.168.178.51:46384
SERVER <--- DB-QUERY: SELECT DATA      <--- 192.168.178.51:46384
SERVER ---> RETURNED DATA              ---> 192.168.178.51:46384
SERVER <--- LOGOUT REQUEST             <--- 192.168.178.51:46384
SERVER ---> RETURNED STATUS            ---> 192.168.178.51:46384
SERVER <-x- DISCONNECTED               -x-> 192.168.178.51:46384
SERVER ---> LOGGED OUT                 ---> 192.168.178.51:46384
SERVER <-x- TCP RESET                  -x-> UNKNOWN
SERVER <-x- DISCONNECTED               -x-> UNKNOWN
SERVER <-x- TCP RESET                  -x-> UNKNOWN
SERVER <-x- DISCONNECTED               -x-> UNKNOWN

```
